apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: parent-app
  namespace: test-jyo2
spec:
  destination:
    name: ''
    namespace: test-jyo2
    server: https://kubernetes.default.svc
  source:
    path: simple-app
    repoURL: https://github.com/jyotsanaarora/gitops-certification-examples.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy: {}

